# top_in.yaml
clk: aclk
rstn: arstn
aximm:
  name: frame
  addr_w: 48
  data_w: 64
streams_out:
  - { name: frame1_stream, width: 17 }
  - { name: frame2_stream, width: 17 }
  - { name: frame3_stream_a, width: 17 }
  - { name: frame3_stream_b, width: 17 }
  - { name: frame4_stream, width: 17 }
  - { name: frame5_stream, width: 17 }
packing: 128
options:
  include_route: True
