# fc1.yaml
clk: aclk
rstn: arstn
streams_in:
  - { name: in_stream, width: 128 }
  - { name: weight_stream, width: 8 }
  - { name: bias_stream, width: 8 }
streams_out:
  - { name: out_stream, width: 8 }
packing: 256
